# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3ba9190dfddaac933b9d64f73e30700f2edd98d23b29f754a74e49c318c1c5aa98863be6b21a82bf688b0a6938f6aaa62c051bd18f9b1ad4562f01d5cf413d7

test:
  secret_key_base: 265a5928d5f8bb8532bb611a83f1ed3ee7bb911628a842830808e2cb1bcce311fe46721d295d92bd92b2f5730ce4d4234ed9234152f10ea6cda944fe1c2c81aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
